version: '2'
services:

    #####################
    # LARAVEL
    #####################
    laravel:
        build         : ./build/
        links         :
            - db
        volumes       :
            - ./html/:/var/www/html/
        ports:
            - 8000:80

    #####################
    # ADMINER
    #####################
    adminer:
        image: dehy/adminer:latest
        ports:
            - 3333:80
        depends_on:
            - db
        links:
            - db

    #####################
    # DATABASE
    #####################
    db:
        image         : mariadb:latest
        volumes       :
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel